yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: "node-modules"
npmRegistryServer: "http://0.0.0.0:4873/"
httpRetry: 10
httpTimeout: 100000
# networkConcurrency: 2
unsafeHttpWhitelist: 
  - "0.0.0.0"
  - localhost