version: '3.1'

services:
  local_verdaccio:
    image: verdaccio/verdaccio
    container_name: "local_verdaccio"
    networks:
      - my-net
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/config:/verdaccio/conf"
      - "./verdaccio/plugins:/verdaccio/plugins"  
networks:
  my-net:
    name: my-net